name: Docker Image build flow CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: cn-demo
  DOCKER_REPO_NAME: omerdahan/cn_test
  DOCKER_TAG: dev-${{ github.run_number }}
  MEND_ORG_UUID: ${{ secrets.MEND_ORG_UUID }}
  MEND_USER_KEY: ${{ secrets.MEND_USER_KEY }}
  MEND_URL: ${{ vars.MEND_URL }}
  MEND_EMAIL: ${{ vars.MEND_EMAIL }}
  MEND_CN_UAT: true

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: Build the Docker image
      run: |
        docker buildx build --platform=linux/arm64 . --file Dockerfile --tag $DOCKER_REPO_NAME:$DOCKER_TAG --load
        docker images

    - name: Download Mend CLI
      run: |
          curl -LO https://downloads.mend.io/cli/linux_amd64/mend
          chmod +x mend
          echo "Download Finished.."
          
    - name: Run an image Scan
      run: |
          echo "Scanning your image with mend CLI scanner..."
          ./mend image $DOCKER_REPO_NAME:$DOCKER_TAG --format sarif --filename results.sarif --filter high,critical
          echo "Scan Finished with code: $?"
      
    - name: Upload sarif
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: results.sarif

    
    - name: Auth to ECR
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_KEY }}
        aws-region: eu-north-1
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Push the Docker image to ECR registry
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: cn-demo
      run: |
        docker tag $DOCKER_REPO_NAME:$DOCKER_TAG $ECR_REGISTRY/$DOCKER_IMAGE_NAME:$DOCKER_TAG
        docker push $ECR_REGISTRY/$DOCKER_IMAGE_NAME:$DOCKER_TAG

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push the Docker image to DockerHub
      run: |
        docker push $DOCKER_REPO_NAME:$DOCKER_TAG
        


      
          
