name: Add Mend custom Docker Labels

on:
  workflow_dispatch:

jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if lables exist & Assign Mend Labels
        run: |

          find . -type f -name "*Dockerfile*" | while read file; do
              if ! grep -qE '^LABEL (org.opencontainers.image.source=|io.mend.image.dockerfile.path=)' "$file"; then
                echo "Updating: $file"
              	echo -e "\nLABEL org.opencontainers.image.source=\"https://github.com/${{ github.repository }}/\"" >> "$file"
                echo -e "LABEL io.mend.image.dockerfile.path=\"${file#./}\"" >> "$file"
              else
                echo "$file is already containing these labels.."
              fi
          done

      - name: Create Pull Request
        if: success()
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Add labels to Dockerfile
          title: '[AUTO] Update Dockerfile Labels'
          body: 'This PR automatically adds Mend labels to the Dockerfile.'
          branch: 'Security/update-dockerfile-labels-with-mend'
          branch-suffix: timestamp
          delete-branch: true

