name: Add Mend custopm Docker Labels

on:
  workflow_dispatch:

jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if lables exist
        run: |
          # Initialize variables to hold files with and without labels
          with_labels=""
          without_labels=""
          
          # Find all files that contain 'Dockerfile' in their names
          find . -type f -name "*Dockerfile*" -print0 | while IFS= read -r -d $'\0' file; do
              # Check each file for the specified labels
              if grep -qE '^LABEL (org.opencontainers.image.source=|io.mend.image.dockerfile.path=)' "$file"; then
                  with_labels+="$file\n"
                  echo -e "$without_labels"
              else
                  without_labels+="$file\n"
                  echo -e "$without_labels"
              fi
          done
          
          echo "output results"
          # Output results
          if [ -n "$with_labels" ]; then
              echo "Labels already exist in:"
              echo -e "$with_labels"
          else
              echo "No files with specified labels found."
          fi

          echo "labels assign"
          if [ -n "$without_labels" ]; then
              echo "Files without the specified labels:"
              echo -e "$without_labels"
              
              
              # Loop through each file without labels and add labels
              echo -e "$without_labels" | while IFS= read -r file; do
                  if [[ -n "$file" ]]; then
          			      echo LABEL org.opencontainers.image.source=https://github.com/${{ github.repository }}/tree/main" >> "$file"
                      echo LABEL io.mend.image.dockerfile.path="$file" >> "$file"
                      
                      echo "Added labels to $file"
                  fi
              done
          else
              echo "All Dockerfiles contain the specified labels."
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Add labels to Dockerfile
          title: '[AUTO] Update Dockerfile Labels'
          body: 'This PR automatically adds labels to the Dockerfile.'
          branch: 'feature/update-dockerfile-labels'
          branch-suffix: timestamp
          delete-branch: true

