name: Add Mend custopm Docker Labels

on:
  push:
    paths:
      - '**/Dockerfile'
  workflow_dispatch:

jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check existing labels
        run: |
          find . -type f -name "Dockerfile" -exec grep -q '^LABEL org.opencontainers.image.source=' {} \; && echo "Labels already exist" || echo "Labels not found"

      - name: Add labels
        run: |
          find . -type f -name "Dockerfile" -exec sed -i '/^LABEL org.opencontainers.image.source=/!s/^LABEL /LABEL org.opencontainers.image.source=https:\/\/github.com\/your_username\/your_repository /; /^LABEL io.mend.image.dockerfile.path=/!s/^LABEL /LABEL io.mend.image.dockerfile.path=$(dirname {})/' {} +
