name: alpine upload existing sarif

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
      
    - name: Upload sarif
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: alpine.sarif
